### PR TITLE
ci: dispatch release note

### PR DESCRIPTION
**Pull request by shmpwk**
## PR Type

- New Feature

## Related Links

https://github.com/tier4/autoware.universe/pull/313
https://github.com/tier4/autoware.universe/pull/315

## Description

This workflow triggers the repository: [TIER4_INTERNAL_LINK](https://github.com/tier4/update-release-notes) to update the spreadsheets for release note. 
The timing of this repository dispatch is committing to tier4/main default branch .

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by shmpwk** [comment]
This CI has already checked in autoware.universe, so just approval might be ok without thorough checking
Also, you cannot checkt CI without merging this.

**Comment by shmpwk** [comment]
@tkimura4 @1222-takeshi @taikitanaka3 
friendly reminder

**Review by 1222-takeshi — APPROVED** [review]
LGTM

**Comment by shmpwk** [comment]
Thanks!

**Pull request merged**
